language: php
php:
  - 5.3
env:
  global:
    # SAUCE
    - secure: "fwebeORlyqO1sXaOVSx7sxeAlmWr6q68RpZWSWmp5Kdu3XcfhV/v3jcH2nIpfDLkFq2rtQw1h+dRcSdHClYedDnr/Vp9fKMkscroNWTn+QqYAJtZTWZIDs3B0B+Ea3wNc1chN7iOXdr2wrz+aX7fyw8olSoEz/+lTBNnJEJovlM="
    - secure: "jlcxYPI1ndqrAV/+IVzFf/BtL0W0oxnFAgl52wFkkgH8c2DHG8Cf2vIF7JVZs0+fhjamuyAiLO9dktowSaWA/SXXbZIBap+DKPpHCp3gjGfXlLF1wwUTT+m5PAMtsoHCs4m3yjTdyAH/Foa8uEbkcZ+mdLEjrcQV8ZxosTSl1jk="
  matrix:
    - TEST_GROUP=unit
    - TEST_GROUP=Sauce
#matrix:
#    allow_failures:
#        - env: "TEST_GROUP=other"
before_script:
  - cd phpunit
  - ./travis-db-create.sh
  - composer --prefer-source install # prefer-source is used to avoid github api limit
#  - ./travis-nginx-install.sh
  - ./travis-apache-install.sh
  - sh -c "if [ $TEST_GROUP = "Sauce" ]; then curl https://gist.githubusercontent.com/santiycr/5139565/raw/sauce_connect_setup.sh | bash; fi"

script: ./travis-tests.sh
